name: gql_transform_link
version: 0.2.2+1
description: GQL Link to transform Requests and Responses. May be used to update context, document, variables, data, errors, etc.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  gql_exec:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: links/gql_link
dev_dependencies: 
  gql: ^0.14.0
  gql_pedantic: ^1.0.2
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2
