name: gql_link
version: 0.5.1
description: A simple and modular AST-based GraphQL request execution interface.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  gql:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: gql
  gql_exec:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: links/gql_exec
  meta: ^1.1.7
dev_dependencies: 
  gql_pedantic: ^1.0.2
  mockito: ^5.0.16
  test: ^1.16.2
