name: gql_dio_link
version: 0.3.0
description: Similar to gql_http_link, gql_dio_link is a GQL Terminating Link to execute requests via Dio using JSON
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  dio: ^5.0.0
  gql:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: gql
  gql_exec:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: links/gql_exec
  gql_link:
    git:
      url: https://github.com/HuukSocial/gql.git
      path: links/gql_link
  meta: ^1.3.0
dev_dependencies: 
  build_runner: ^2.0.0
  code_builder: ^4.2.0
  collection: ^1.15.0
  gql_pedantic: ^1.0.2
  http_parser: ^4.0.0
  mockito: ^5.3.0
  test: ^1.14.3
